In [30]:
import numpy as np
import pandas as pd
import math

In [31]:
data = pd.read_table(r'ToyotaCorolla (1).txt',sep='\t')

In [32]:
data

Id  Price  Age_08_04     KM    cc  Doors  Weight
0        1  13500         23  46986  2000      3    1165
1        2  13750         23  72937  2000      3    1165
2        3  13950         24  41711  2000      3    1165
3        4  14950         26  48000  2000      3    1165
4        5  13750         30  38500  2000      3    1170
...    ...    ...        ...    ...   ...    ...     ...
1431  1438   7500         69  20544  1300      3    1025
1432  1439  10845         72  19000  1300      3    1015
1433  1440   8500         71  17016  1300      3    1015
1434  1441   7250         70  16916  1300      3    1015
1435  1442   6950         76      1  1600      5    1114

[1436 rows x 7 columns]

In [33]:
data1 = data[['Price','Age_08_04','KM','cc','Doors','Weight']]

In [69]:
np_data = np.array(data1)

In [70]:
np_data

array([[13500,    23, 46986,  2000,     3,  1165],
       [13750,    23, 72937,  2000,     3,  1165],
       [13950,    24, 41711,  2000,     3,  1165],
       ...,
       [ 8500,    71, 17016,  1300,     3,  1015],
       [ 7250,    70, 16916,  1300,     3,  1015],
       [ 6950,    76,     1,  1600,     5,  1114]], dtype=int64)

In [92]:
def train_test_split(Data ,test_size=0.3,random=False,random_seed=None):
    
    length = len(Data)
    index=np.array(range(length))
    test_size_len = math.ceil(length*test_size)
    
    if (random):   
        rs = np.random.RandomState(random_seed)
        rs.shuffle(index)
    
    temp_list = []
    
    for i in range(length):
        temp_list.append(Data[index[i]])
        
    train = np.array(temp_list[test_size_len:])
    test = np.array(temp_list[:test_size_len])
    
    train_x = train[1:]
    train_y = train[0]
    test_x = test[1:]
    test_y = test[0]
    
    return train_x,train_y, train_x, test_y

In [101]:
train_x ,train_y, train_x, test_y = train_test_split(np_data, random =True , random_seed = 100)
train_x

array([[  7600,     78,  36000,   1600,      3,   1050],
       [  8950,     54, 149329,   2000,      5,   1135],
       [ 10950,     57,  80470,   1600,      5,   1085],
       ...,
       [ 11895,     39,  27170,   1400,      5,   1060],
       [ 14900,     30,  22000,   1400,      5,   1110],
       [  7750,     68,  74875,   1600,      5,   1070]], dtype=int64)

MLR

$ \hat{w} = (x^{t}*x)^{-1}x^{t}y $

In [ ]:
class MLR:
    
    def __init__(self,intercept=True):
        self.ceof_=None
        
        # y절편 구하는 기능
        self.intercept = intercept
        
    def fit(self,X,Y):
        
        if self.intercept:
            new_input_x = self.intercept_add(X)
        else:
            new_input_x = X
            
        # w hat구하기 // 위의 식과 같다.
        self.coef_ = np.linalg.inv(new_input_x.tanspose() * new_input_x)* new_input_x.transpose()*Y
        
        #y 절편 구하기 위해서 맨 마지막에 1을 추가// y = wx+b 에서 b(절편)의 역할
    def intercept_add(self,X):
        
        # X데이터 길이만큼의 1로 만들어진 배열 생성
        # reshape(-1,1) 로 행렬 재구성 // 1개씩 들어가는 2차원 배열 생성
        
        ones = np.ones(X.shape[0]).reshape(-1,1)
        # X데이터에 1로 구성된 행렬 붙이기
        result = np.concatenate([X,ones],axis=1)
        
        return result

[np.shape 관련](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

In [105]:
ones = np.ones((train_x.shape[0])).reshape(-1,1)
ones

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]])

In [112]:
print(train_x.shape)
train_x

(1004, 6)


array([[  7600,     78,  36000,   1600,      3,   1050],
       [  8950,     54, 149329,   2000,      5,   1135],
       [ 10950,     57,  80470,   1600,      5,   1085],
       ...,
       [ 11895,     39,  27170,   1400,      5,   1060],
       [ 14900,     30,  22000,   1400,      5,   1110],
       [  7750,     68,  74875,   1600,      5,   1070]], dtype=int64)

In [113]:
re = np.concatenate([train_x,ones],axis=1)
print(re.shape)
# 1을 추가된 것을 확인 할 수 있다.
re

(1004, 7)


array([[7.60000e+03, 7.80000e+01, 3.60000e+04, ..., 3.00000e+00,
        1.05000e+03, 1.00000e+00],
       [8.95000e+03, 5.40000e+01, 1.49329e+05, ..., 5.00000e+00,
        1.13500e+03, 1.00000e+00],
       [1.09500e+04, 5.70000e+01, 8.04700e+04, ..., 5.00000e+00,
        1.08500e+03, 1.00000e+00],
       ...,
       [1.18950e+04, 3.90000e+01, 2.71700e+04, ..., 5.00000e+00,
        1.06000e+03, 1.00000e+00],
       [1.49000e+04, 3.00000e+01, 2.20000e+04, ..., 5.00000e+00,
        1.11000e+03, 1.00000e+00],
       [7.75000e+03, 6.80000e+01, 7.48750e+04, ..., 5.00000e+00,
        1.07000e+03, 1.00000e+00]])

In [ ]:
MSE_list = []
for i in range:
    예측 하는 함수 실행
    MSE_list.append(np.mean((Y-Y^hat)**2))
    MSE를 리스트로 저장 가능