In [1]:
import numpy as np

In [32]:
data = [1,2,3.3]
data1 = [[1,2],[2,3],[3,4]]
data2 = [[[1,2],[2,3],[3,4]],[[1,2],[2,3],[3,4]]]

In [33]:
a = np.array(data2)

In [34]:
a

array([[[1, 2],
        [2, 3],
        [3, 4]],

       [[1, 2],
        [2, 3],
        [3, 4]]])

In [35]:
# array 자료 구조이며 객체이다 
# 속성과 메소드를 갖는다
print(type(a))

# 차원의 수
print(a.ndim)

# 배열의 구조
# 뒤에부터 X Y Z 순으로 생각하면 된다
# data2 기준 (2,3,2) 이면 2개짜리 3개묶음이 2개 있다.
print(a.shape)

# 요소의 개수
print(a.size)

print(a.dtype)

# 바이트 단위의 사이즈
print(a.itemsize)

<class 'numpy.ndarray'>
3
(2, 3, 2)
12
int32
4


In [44]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [45]:
a+b

array([5, 7, 9])

In [46]:
# 차원이 달라도 계산 가능하다// 1차원의 개수가 같으면 가능
a = np.array([[1,2,3],[1,2,3]])

In [47]:
a+b

array([[5, 7, 9],
       [5, 7, 9]])

In [48]:
a = np.array([[1,2],[3,4]]) # 2 x 2 형태
b = np.array([[10,20],[30,40]])

In [52]:
# matmul 과 @는 같은 의미
# 만일 하나는 int32 이고 하나는 int 64이면 계산시 int64가 된다
print(np.matmul(a,b))
print(a@b)

[[ 70 100]
 [150 220]]
[[ 70 100]
 [150 220]]


In [53]:
a = np.array([1,2,3,'a'])

In [54]:
print(a.ndim)
print(a.size)
print(a.shape)
print(a.itemsize)
print(a.type)

1
4
(4,)
44


AttributeError: 'numpy.ndarray' object has no attribute 'type'